[project]
name = "day2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ipython>=8.12.3",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "primepy>=1.3",
    "sympy>=1.13.3",
]
